language: java

sudo: false
dist: trusty

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

install:
- java -version
- export GRADLE_OPTS="-Dorg.gradle.daemon=false --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED"
- mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
# - export GRADLE_OPTS="--permit-illegal-access" # not supported in b162, yet
- ./gradlew -version

script:
- ./gradlew --no-daemon --stacktrace check
